CREATE TABLE GAME(
  ID    SERIAL PRIMARY KEY,
  NAME  VARCHAR(255),
  PRICE INTEGER,
  RELEASE DATE,
  UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DESCLIPTION TEXT
);

CREATE TABLE IMAGES(
  ID      SERIAL PRIMARY KEY,
  GAME_ID INTEGER,
  IMAGE_DATA BYTEA,
  UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USER(
  ID       SERIAL PRIMARY KEY,
  NAME     VARCHAR(255),
  ACCOUNT  VARCHAR(255),
  PASSWORD VARCHAR(255),
  UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
